TERMUX_PKG_HOMEPAGE=https://www.salome-platform.org
TERMUX_PKG_DESCRIPTION="MED file format library for scientific data exchange"
TERMUX_PKG_LICENSE=LGPL2.1
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=4.1.0
TERMUX_PKG_SRCURL=https://files.salome-platform.org/Salome/other/med-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=b6b7f6f77b02073aa710ae8eb35625a521c69a726895a833aea6317722a003b8
TERMUX_PKG_DEPENDS="hdf5, gfortran"
TERMUX_PKG_BUILD_DEPENDS="cmake, ninja"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_BUILD_TYPE=Release
-DMEDFILE_INSTALL_DOC=OFF
-DMEDFILE_BUILD_PYTHON=OFF
-DMEDFILE_BUILD_TESTS=OFF
-DMEDFILE_USE_MPI=OFF
"
